import { STRINGS } from '../utils/strings'

export const EMPLOYEE_TOUR_STEPS = [
  {
    title: STRINGS.TOUR_EMPLOYEE_WELCOME_TITLE,
    body: STRINGS.TOUR_EMPLOYEE_WELCOME_BODY,
  },
  {
    title: STRINGS.TOUR_EMPLOYEE_ASSIGNMENT_TITLE,
    body: STRINGS.TOUR_EMPLOYEE_ASSIGNMENT_BODY,
  },
  {
    title: STRINGS.TOUR_EMPLOYEE_PUNCHES_TITLE,
    body: STRINGS.TOUR_EMPLOYEE_PUNCHES_BODY,
  },
  {
    title: STRINGS.TOUR_EMPLOYEE_CAPTURE_TITLE,
    body: STRINGS.TOUR_EMPLOYEE_CAPTURE_BODY,
  },
  {
    title: STRINGS.TOUR_EMPLOYEE_HISTORY_TITLE,
    body: STRINGS.TOUR_EMPLOYEE_HISTORY_BODY,
  },
  {
    title: STRINGS.TOUR_EMPLOYEE_OFFLINE_TITLE,
    body: STRINGS.TOUR_EMPLOYEE_OFFLINE_BODY,
  },
]

export const ADMIN_TOUR_STEPS = [
  {
    title: STRINGS.TOUR_ADMIN_WELCOME_TITLE,
    body: STRINGS.TOUR_ADMIN_WELCOME_BODY,
  },
  {
    title: STRINGS.TOUR_ADMIN_SNAPSHOT_TITLE,
    body: STRINGS.TOUR_ADMIN_SNAPSHOT_BODY,
  },
  {
    title: STRINGS.TOUR_ADMIN_ACTIONS_TITLE,
    body: STRINGS.TOUR_ADMIN_ACTIONS_BODY,
  },
  {
    title: STRINGS.TOUR_ADMIN_ASSIGNMENTS_TITLE,
    body: STRINGS.TOUR_ADMIN_ASSIGNMENTS_BODY,
  },
  {
    title: STRINGS.TOUR_ADMIN_REVIEW_TITLE,
    body: STRINGS.TOUR_ADMIN_REVIEW_BODY,
  },
  {
    title: STRINGS.TOUR_ADMIN_SETUP_TITLE,
    body: STRINGS.TOUR_ADMIN_SETUP_BODY,
  },
]