// Centralized i18n-ready strings for VanTrack
// Easy to translate to Hindi/Marathi later

export const STRINGS = {
  // App
  APP_NAME: 'VanTrack',
  APP_SUBTITLE: 'Forest Field Operations',

  // Auth
  LOGIN: 'Login',
  LOGOUT: 'Logout',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  PHONE: 'Phone',
  SIGN_UP: 'Sign Up',
  FORGOT_PASSWORD: 'Forgot Password',
  RESET_PASSWORD: 'Reset Password',
  REMEMBER_ME: 'Remember me',
  LOGIN_ERROR: 'Login failed. Please check your credentials.',
  SIGNUP_ERROR: 'Sign up failed. Please try again.',
  SIGNUP_RATE_LIMIT:
    'Too many sign-up attempts. Supabase limits sign-ups on the free tier (about 2 confirmation emails/hour). Wait a few minutes, then log in if the account already exists, or create the user in Supabase Dashboard → Authentication.',
  SIGNUP_EMAIL_EXISTS: 'An account with this email already exists. Try logging in instead.',
  CONFIRM_EMAIL_SENT: 'Account created. Check your email to confirm before logging in.',
  FORGOT_PASSWORD_HINT: 'Enter your email and we will send a password reset link.',
  SEND_RESET_LINK: 'Send Reset Link',
  RESET_EMAIL_SENT: 'Password reset email sent. Check your inbox.',
  BACK_TO_LOGIN: 'Back to Login',
  ADMIN_CREATES_ACCOUNTS: 'Contact your admin to get an account.',
  NEW_PASSWORD: 'New Password',
  CONFIRM_PASSWORD: 'Confirm Password',
  PASSWORDS_DONT_MATCH: 'Passwords do not match',
  UPDATE_PASSWORD: 'Update Password',
  PASSWORD_UPDATED: 'Password updated. Redirecting to login...',
  RESET_PASSWORD_HINT: 'Choose a new password for your account.',
  RESET_LINK_INVALID: 'This reset link is invalid or expired. Request a new one from the login page.',
  TEMP_PASSWORD: 'Temporary Password',
  CREATE_THEN_SELFIE_HINT: 'After creating the account, use Edit to capture a reference selfie.',
  UNEXPECTED_ERROR: 'Something went wrong. Please reload the app.',
  RELOAD_APP: 'Reload App',
  INSTALL_APP: 'Install App',
  INSTALL_APP_TITLE: 'Install VanTrack',
  INSTALL_APP_HINT: 'Add to your home screen for quick check-in access.',
  NOT_NOW: 'Not Now',
  REFRESH: 'Refresh',
  REFRESHING: 'Refreshing...',
  LAST_UPDATED: 'Updated',

  // Employee Dashboard
  TODAY_STATUS: "Today's Status",
  CHECK_IN: 'Check In',
  MIDDAY: 'Midday Verification',
  CHECK_OUT: 'Check Out',
  PENDING: 'Pending',
  COMPLETED: 'Completed',
  HOURS_WORKED: 'Hours Worked',

  // Punch
  TAKE_SELFIE: 'Take Selfie',
  CAPTURE: 'Capture',
  RETAKE: 'Retake',
  ALLOW_CAMERA: 'Allow Camera Access',
  ALLOW_LOCATION: 'Allow Location Access',
  GPS_ACCURACY: 'GPS Accuracy',
  METERS: 'meters',
  DISTANCE_FROM_SITE: 'Distance from Site',
  OUTSIDE_GEOFENCE: 'Outside Site Radius',
  UPLOADING: 'Uploading...',
  PUNCH_SUCCESS: 'Punch recorded successfully',
  PUNCH_ERROR: 'Failed to record punch',
  POOR_GPS: 'GPS accuracy poor (>100m). Retry for better accuracy.',
  OFFLINE_SAVED: 'Saved offline. Will sync when online.',
  OFFLINE_MODE: 'You are offline. Punches will be saved locally when you record them.',
  SYNCING_PENDING: 'Syncing pending punches',

  // History & Timesheet
  HISTORY: 'History',
  MY_TIMESHEET: 'My Timesheet',
  VIEW_DAY: 'View Day',
  SELECT_DAY_HINT: 'Select a day from the calendar to view punch details',
  ALL_LOCATIONS: 'All locations',
  NO_DATA: 'No attendance data',
  CALENDAR: 'Calendar',
  PRESENT: 'Present',
  MISSING_MIDDAY: 'Missing Midday',
  FULL_DAY: 'Full Day',
  HALF_DAY: 'Half Day',
  SHORT_DAY: 'Short Day',
  ABSENT: 'Absent',

  // Admin
  ADMIN_DASHBOARD: 'Admin Dashboard',
  TODAY_VIEW: "Today's Attendance",
  REVIEW_QUEUE: 'Review Queue',
  EMPLOYEES: 'Employees',
  SITES: 'Sites',
  TIMESHEETS: 'Timesheets',
  INSIGHTS: 'Insights & Reports',
  ACTIVE_EMPLOYEES: 'Active Employees',
  TODAYS_ATTENDANCE: "Today's Attendance",
  DAILY_HOURS_TREND: 'Daily Hours Trend',
  HOURS_BY_SITE: 'Hours by Site',
  EMPLOYEE_LEADERBOARD: 'Employee Leaderboard',
  DAILY_BREAKDOWN: 'Daily Breakdown',
  FLAGGED_PUNCHES: 'Flagged Punches',
  APPROVE: 'Approve',
  REJECT: 'Reject',
  COMMENT: 'Comment',
  ADD_EMPLOYEE: 'Add Employee',
  ADD_SITE: 'Add Site',
  EDIT: 'Edit',
  DELETE: 'Delete',
  SAVE: 'Save',
  APPLY: 'Apply',
  CANCEL: 'Cancel',
  REFERENCE_SELFIE: 'Reference Selfie',
  PUNCH_PHOTO: 'Punch Photo',
  UPLOAD: 'Upload',
  MANDATORY_HOURS: 'Mandatory Hours/Day',
  ASSIGNED_SITE: 'Assigned Site',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
  DEACTIVATE: 'Deactivate',
  ACTIVATE: 'Activate',
  REACTIVATE: 'Reactivate',
  ACCOUNT_ACTIVE: 'Account is active — employee can log in and punch',
  ACCOUNT_INACTIVE: 'Account is inactive — employee cannot log in or punch',
  SITE_ACTIVE: 'Site is active — assignments and punches allowed',
  SITE_INACTIVE: 'Site is inactive — no new punches at this location',
  SHOW_INACTIVE: 'Show inactive',
  STATUS: 'Status',
  FULL_NAME: 'Full Name',
  ACTIONS: 'Actions',
  TIME: 'Time',
  INACTIVE_ACCOUNT: 'Account Deactivated',
  INACTIVE_ACCOUNT_MSG: 'Your account has been deactivated. Contact your admin.',
  ENROLLMENT_HINT:
    'Create employee accounts here. Employees capture their reference selfie on first login; use Edit to update details or re-capture if needed.',
  NO_REFERENCE_SELFIE: 'No reference selfie on file',
  CAPTURE_REFERENCE_SELFIE: 'Capture Reference Selfie',
  MAP_PICKER_HINT: 'Click the map, drag the marker, search, or enter coordinates below',
  SEARCH_LOCATION: 'Search location',
  SEARCH_SITES: 'Search sites',
  SEARCH_EMPLOYEES: 'Search employees',
  LOCATION_SEARCH_FAILED: 'Could not search locations. Try again.',
  PASTE_COORDINATES: 'Paste coordinates',
  PASTE_COORDINATES_HINT: 'Paste "latitude, longitude" from Google Maps or GPS',
  COORDINATES_INVALID: 'Enter valid latitude (-90 to 90) and longitude (-180 to 180)',
  SITE_NAME_REQUIRED: 'Site name is required',
  PIN_LOCATION: 'Pin location on map',

  // Map
  SITE_LOCATION: 'Site Location',
  SITE_NAME: 'Site Name',
  RADIUS: 'Radius (meters)',
  MAP: 'Map',
  LATITUDE: 'Latitude',
  LONGITUDE: 'Longitude',
  DECIMAL_COORDINATES: 'Decimal coordinates',

  // Timesheet
  EXPORT_CSV: 'Export CSV',
  EXPORT_XLSX: 'Export XLSX',
  GENERATE: 'Generate',
  FILTER: 'Filter',
  EMPLOYEE: 'Employee',
  SITE: 'Site',
  DATE_RANGE: 'Date Range',
  FROM: 'From',
  TO: 'To',
  TOTAL_HOURS: 'Total Hours',
  TOTAL_DAYS: 'Total Days',

  // Errors & Validation
  ERROR: 'Error',
  SUCCESS: 'Success',
  WARNING: 'Warning',
  REQUIRED: 'This field is required',
  INVALID_EMAIL: 'Invalid email address',
  PASSWORD_TOO_SHORT: 'Password must be at least 6 characters',
  NETWORK_ERROR: 'Network error. Please check your connection.',
  SERVER_ERROR: 'Server error. Please try again later.',
  CREATE_EMPLOYEE_FUNCTION_MISSING:
    'Employee creation service is not deployed. Deploy the create-employee Supabase Edge Function (see supabase/README.md).',
  CREATE_EMPLOYEE_ASSIGNMENT_FAILED:
    'Employee account was created, but site assignment failed. Open the employee and assign a site manually.',
  NOT_FOUND: 'Not found',
  UNAUTHORIZED: 'Unauthorized. Please login.',
  FORBIDDEN: 'Forbidden. You do not have permission.',

  // Flags
  FLAG_OUTSIDE_GEOFENCE: 'Outside Site Radius',
  FLAG_POOR_GPS: 'Poor GPS Accuracy',
  FLAG_TIME_MISMATCH: 'Device Time Mismatch',
  FLAG_SYNCED_LATE: 'Synced Late',
  FLAG_NO_MIDDAY: 'Missing Midday Verification',
  FLAG_NO_CHECK_IN: 'No Check-in for This Day',
  FLAG_FACE_MISMATCH: 'Face Does Not Match Reference Selfie',
  FLAG_NO_FACE_DETECTED: 'No Face Detected in Photo',
  FLAG_NO_ACTIVE_ASSIGNMENT: 'No Active Site Assignment',
  FLAG_OUTSIDE_ASSIGNED_SITE: 'Outside Assigned Site Geofence',
  SITE_ASSIGNMENTS: 'Site Assignments',
  STAFF_SITE_MAPPING: 'Staff & Site Mapping',
  TODAY_SNAPSHOT: "Today's Snapshot",
  QUICK_ACTIONS: 'Quick Actions',
  TOTAL: 'Total',
  PERIOD: 'Period',
  EDIT_ASSIGNMENT: 'Edit Assignment',
  ASSIGNMENT_FIELDS_REQUIRED: 'Select both employee and site',
  ASSIGNMENT_FORM_HINT: 'Employees can only punch at assigned sites during the active period.',
  ASSIGNMENTS_PAGE_HINT: 'Map field staff to forest sites with start and end dates. Punch access is enforced by these assignments.',
  TIMESHEET_PAGE_HINT: 'Payroll register for the selected period. Expand any row for daily breakdown and punch details.',
  ASSIGNMENT_REPORT: 'Assignment Report',
  ADD_ASSIGNMENT: 'Add Assignment',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  ONGOING: 'Ongoing',
  ACTIVE_NOW: 'active now',
  ASSIGNED_STAFF: 'Assigned Staff',
  SITE_DETAIL_HINT: 'View location, geofence, and staff assignments',
  NO_ASSIGNMENTS: 'No staff assigned to this site yet',
  CONFIRM_DELETE_ASSIGNMENT: 'Remove this site assignment?',
  EMPLOYEE_REQUIRED: 'Select an employee',
  ASSIGNMENT_NOTES: 'Notes (optional)',
  NO_ACTIVE_ASSIGNMENT: 'You have no active site assignment for today. Contact your admin.',
  ACTIVE_ASSIGNMENTS: 'Active Assignments Today',
  ATTENDANCE_TAB: 'Attendance',
  ASSIGNMENTS_TAB: 'Assignments',
  SELECT_EMPLOYEE_HINT: 'Select an employee to view their timesheet',
  REFERENCE_SELFIE_SETUP: 'Set Up Your Reference Selfie',
  REFERENCE_SELFIE_SETUP_HINT:
    'Before your first punch, capture a clear front-facing selfie. This photo is used to verify your identity on every check-in, midday, and check-out.',
  REFERENCE_SELFIE_STAMP_HINT:
    'A verified attendance stamp with date, IST time, GPS location, and accuracy will be added to your photo.',
  REFERENCE_SELFIE_FAILED: 'Could not save reference selfie. Please try again.',
  REFERENCE_SELFIE_REQUIRED: 'Complete reference selfie setup before punching.',
  NO_FACE_DETECTED: 'No face detected. Face the camera in good light and try again.',
  FACE_MISMATCH_RECORDED:
    'Punch recorded but your face did not match your reference selfie. An admin will review it.',
  NO_FACE_FLAGGED: 'Punch recorded but no face was detected. An admin will review it.',
  FACE_MATCH_SCORE: 'Face Match Score',
  LOCATION_REQUIRED: 'Location is required. Enable GPS and try again.',
  CAMERA_DENIED: 'Camera permission is required. Enable it in your browser settings.',
  NO_SITE_ASSIGNED: 'No site assigned yet. Contact your admin before punching.',
  PUNCH_STAMP_HINT:
    'Each punch photo includes a verified stamp with date, IST time, GPS coordinates, and location accuracy.',
  PUNCHES: 'Punches',

  // App tour
  TOUR_SKIP: 'Skip tour',
  TOUR_REPLAY: 'App tour',
  TOUR_GET_STARTED: 'Get started',
  TOUR_STEP_OF: 'Step {current} of {total}',
  TOUR_EMPLOYEE_WELCOME_TITLE: 'Welcome to VanTrack',
  TOUR_EMPLOYEE_WELCOME_BODY:
    'This quick guide shows how to record your daily field attendance. It only appears once — you can replay it anytime from the header.',
  TOUR_EMPLOYEE_ASSIGNMENT_TITLE: 'Your site assignment',
  TOUR_EMPLOYEE_ASSIGNMENT_BODY:
    'You can only punch when an admin has assigned you to a forest site for today. Your active sites appear at the top of the dashboard.',
  TOUR_EMPLOYEE_PUNCHES_TITLE: 'Three daily punches',
  TOUR_EMPLOYEE_PUNCHES_BODY:
    'Tap Check In when you arrive, Midday Verification around lunch, and Check Out when you leave. Midday and check-out unlock after a valid check-in.',
  TOUR_EMPLOYEE_CAPTURE_TITLE: 'Selfie & GPS',
  TOUR_EMPLOYEE_CAPTURE_BODY:
    'Each punch opens your front camera for a live selfie — no gallery uploads. GPS must be on; stay within your site geofence for a clean record.',
  TOUR_EMPLOYEE_HISTORY_TITLE: 'View your history',
  TOUR_EMPLOYEE_HISTORY_BODY:
    'Open My Timesheet to see past days on a calendar. Tap any day for punch times, photos, and any flags that need admin review.',
  TOUR_EMPLOYEE_OFFLINE_TITLE: 'Works offline too',
  TOUR_EMPLOYEE_OFFLINE_BODY:
    'No signal in the forest? Punches save on your phone and sync automatically when you are back online.',
  TOUR_ADMIN_WELCOME_TITLE: 'Welcome, admin',
  TOUR_ADMIN_WELCOME_BODY:
    'VanTrack helps you monitor field teams, verify punches, and export timesheets. This tour walks through the essentials.',
  TOUR_ADMIN_SNAPSHOT_TITLE: "Today's snapshot",
  TOUR_ADMIN_SNAPSHOT_BODY:
    'The KPI strip shows active staff, attendance rate, site count, and flagged punches waiting for review — refreshed when you open the dashboard.',
  TOUR_ADMIN_ACTIONS_TITLE: 'Quick actions',
  TOUR_ADMIN_ACTIONS_BODY:
    'Use the action list to jump to Today\'s Attendance, Review Queue, Staff & Site Mapping, Timesheets, Insights, Employees, and Sites.',
  TOUR_ADMIN_ASSIGNMENTS_TITLE: 'Assign before they punch',
  TOUR_ADMIN_ASSIGNMENTS_BODY:
    'Employees need a time-bounded site assignment before they can punch. Go to Staff & Site Mapping to assign people to forest sites.',
  TOUR_ADMIN_REVIEW_TITLE: 'Review flagged punches',
  TOUR_ADMIN_REVIEW_BODY:
    'Punches outside the geofence, with poor GPS, face mismatches, or other issues land in the Review Queue. Approve or reject with a comment.',
  TOUR_ADMIN_SETUP_TITLE: 'Set up sites & staff',
  TOUR_ADMIN_SETUP_BODY:
    'Add forest sites with map pins and geofence radius under Sites. Enroll employees under Employees — they capture a reference selfie on first login.',

  // Privacy & compliance
  PRIVACY_POLICY: 'Privacy Policy',
  PRIVACY_CONSENT_TITLE: 'Data processing consent',
  PRIVACY_CONSENT_BODY:
    'VanTrack uses your photo and GPS location to verify field attendance. Please review and consent before continuing.',
  PRIVACY_CONSENT_ITEM_PHOTO: 'Selfie photos for identity verification at each punch',
  PRIVACY_CONSENT_ITEM_LOCATION: 'GPS coordinates to confirm you are at an assigned forest site',
  PRIVACY_CONSENT_ITEM_RETENTION: 'Photos retained per org policy, then purged (see Privacy Policy)',
  PRIVACY_CONSENT_ITEM_RIGHTS: 'You may export your data or request erasure under applicable law (DPDP/GDPR)',
  PRIVACY_CONSENT_CHECKBOX: 'I consent to processing of my photo and location data as described in the',
  PRIVACY_CONSENT_ACCEPT: 'Accept and continue',
  PRIVACY_COMPLIANCE: 'Privacy & Compliance',
  PRIVACY_SETTINGS: 'Privacy settings',
  PRIVACY_SETTINGS_SAVED: 'Privacy settings saved.',
  PHOTO_RETENTION_DAYS: 'Photo retention (days)',
  PRIVACY_POLICY_VERSION: 'Policy version',
  DATA_CONTROLLER: 'Data controller',
  DATA_CONTROLLER_EMAIL: 'Controller email',
  RUN_RETENTION_PURGE: 'Run photo retention purge',
  PRIVACY_PURGE_CONFIRM: 'Purge punch photo references older than the retention period?',
  PRIVACY_PURGE_DONE: 'Purged {n} punch photo reference(s). Storage files may need separate cleanup.',
  PRIVACY_PURGE_HINT: 'Marks old punch photos as purged in the database. Employees on legal hold are skipped.',
  ERASURE_REQUESTS: 'Data erasure requests',
  NO_ERASURE_REQUESTS: 'No erasure requests.',
  APPROVE_ERASURE: 'Approve & erase',
  LEGAL_HOLD_ACTIVE: 'Legal hold — erasure blocked until hold is removed.',
  REMOVE_LEGAL_HOLD: 'Remove legal hold',
  YOUR_DATA_RIGHTS: 'Your data rights',
  YOUR_DATA_RIGHTS_HINT: 'Export a copy of your attendance data or request account erasure.',
  EXPORT_MY_DATA: 'Export my data (JSON)',
  DATA_EXPORT_DONE: 'Data export downloaded.',
  REQUEST_ERASURE: 'Request data erasure',
  REQUEST_ERASURE_HINT: 'Admin must approve. Your account will be deactivated and personal data anonymized.',
  ERASURE_REQUEST_CONFIRM: 'Submit a data erasure request? This cannot be undone after admin approval.',
  ERASURE_REQUEST_SUBMITTED: 'Erasure request submitted. An admin will review it.',
  REASON_OPTIONAL: 'Reason (optional)',
  PRIVACY_TAB: 'Privacy',
  PRIVACY_SECTION_DATA: 'What we collect',
  PRIVACY_SECTION_DATA_BODY:
    'Name, phone, selfie photos, GPS coordinates, punch timestamps, site assignments, and leave records.',
  PRIVACY_SECTION_PURPOSE: 'Why we process it',
  PRIVACY_SECTION_PURPOSE_BODY:
    'To verify field attendance, prevent fraud, support payroll, and meet your employer\'s operational requirements.',
  PRIVACY_SECTION_RETENTION: 'Retention',
  PRIVACY_SECTION_RETENTION_BODY:
    'Punch photo references are purged after {days} days unless a legal hold applies. Attendance metadata may be kept longer for payroll and audit.',
  PRIVACY_SECTION_RIGHTS: 'Your rights',
  PRIVACY_SECTION_RIGHTS_BODY:
    'You may access, export, or request erasure of your data. Contact your data controller for complaints under India DPDP or GDPR where applicable.',
  PRIVACY_SECTION_SECURITY: 'Security',
  PRIVACY_SECTION_SECURITY_BODY:
    'Data is stored in Supabase with row-level security. Photos are in a private bucket with signed URLs. HTTPS is required.',

  // Workforce
  WORKFORCE: 'Leave & Holidays',
  LEAVE_REQUESTS: 'Leave',
  HOLIDAYS: 'Holidays',
  AUDIT_LOG: 'Audit Log',
  AUDIT_LOG_HINT: 'Immutable record of all admin and field activity across the app.',
  SEARCH_AUDIT: 'Search actions, actors, details…',
  NO_AUDIT_ENTRIES: 'No audit entries yet.',
  ENTITY: 'Entity',
  REQUEST_LEAVE: 'Request Leave',
  LEAVE_TYPE: 'Leave Type',
  REASON: 'Reason',
  ON_LEAVE_TODAY: 'You are on approved leave today — punching is disabled.',
  ADMIN_ON_LEAVE_NOTE: 'Approved leave — no punch expected',
  ON_LEAVE: 'On Leave',
  HOLIDAY: 'Holiday',
  HOLIDAY_NAME: 'Holiday name',
  ADD_HOLIDAY: 'Add Holiday',
  ALL_SITES: 'All sites',
  NO_LEAVE_REQUESTS: 'No leave requests yet.',
  ADMIN_COMMENT: 'Admin comment',
  ACTOR: 'Actor',
  ACTION: 'Action',
  DETAILS: 'Details',
  LEAVE_TAB: 'Leave',

  // General
  HOME: 'Home',
  BACK: 'Back',
  NEXT: 'Next',
  PREVIOUS: 'Previous',
  SETTINGS: 'Settings',
  HELP: 'Help',
  ABOUT: 'About',
  CONFIRM: 'Confirm',
  CLOSE: 'Close',
  LOADING: 'Loading...',
}
